### ISSUE TITLE
implement tiled data server

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bdp_controls#12]
The [tiled](https://github.com/bluesky/tiled) data server can be used to access Bluesky measurements from the databroker and/or content from supported data files.

**Comment by prjemian** [comment]
Created the new `tiled` conda environment and activated it.  Got some startup problems.

<details>
<summary>start <em>tiled</em> server, got these errors</summary>

```bash
(tiled) prjemian@zap:~/.../bdp_controls/tiled$ tiled serve config  ./config.yml
Traceback (most recent call last):
  File "/home/prjemian/.local/bin/tiled", line 8, in <module>
    sys.exit(main())
  File "/home/prjemian/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/prjemian/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/prjemian/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/prjemian/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/prjemian/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/prjemian/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/prjemian/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/prjemian/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/prjemian/.local/lib/python3.8/site-packages/tiled/commandline/main.py", line 486, in serve_config
    kwargs = construct_build_app_kwargs(parsed_config, source_filepath=config_path)
  File "/home/prjemian/.local/lib/python3.8/site-packages/tiled/config.py", line 110, in construct_build_app_kwargs
    obj = import_object(import_path, accept_live_object=True)
  File "/home/prjemian/.local/lib/python3.8/site-packages/tiled/utils.py", line 409, in import_object
    module = importlib.import_module(import_path)
  File "/opt/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'databroker.mongo_normalized'
```

</details>


<details>
<summary>list of packages in conda environment</summary>

```
(tiled) prjemian@zap:~/.../bdp_controls/tiled$ conda list
# packages in environment at /home/prjemian/.conda/envs/tiled:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
aiofiles                  0.8.0                    pypi_0    pypi
alembic                   1.7.7                    pypi_0    pypi
anyio                     3.5.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
area-detector-handlers    0.0.8                    pypi_0    pypi
asgiref                   3.5.0                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
blosc                     1.10.6                   pypi_0    pypi
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39h27cfd23_1003  
ca-certificates           2022.2.1             h06a4308_0  
cachetools                5.0.0                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
certifi                   2021.10.8        py39h06a4308_2  
cffi                      1.15.0           py39hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
cryptography              36.0.0           py39h9ce1e76_0  
cycler                    0.11.0             pyhd3eb1b0_0  
dask                      2022.3.0                 pypi_0    pypi
databroker                2.0.0a24                 pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
decorator                 5.1.1              pyhd3eb1b0_0  
ecdsa                     0.18.0b2                 pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
event-model               1.17.2                   pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.4                h295c915_0  
fastapi                   0.75.0                   pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
fsspec                    2022.2.0                 pypi_0    pypi
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h4ff587b_1  
greenlet                  2.0.0a1                  pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h11                       0.12.0                   pypi_0    pypi
h5netcdf                  0.15.0                   pypi_0    pypi
h5py                      3.6.0            py39ha0f2276_0  
hdf5                      1.10.6               hb1b8bf9_0  
heapdict                  1.0.1                    pypi_0    pypi
httpcore                  0.13.7                   pypi_0    pypi
httpie                    2.1.0            py39hf3d152e_2    conda-forge
httptools                 0.4.0                    pypi_0    pypi
httpx                     1.0.0b0                  pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.3                pyhd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
ipython                   8.1.1            py39h06a4308_0  
jedi                      0.18.1           py39h06a4308_1  
jinja2                    3.0.3                    pypi_0    pypi
jmespath                  1.0.0                    pypi_0    pypi
jpeg                      9d                   h7f8727e_0  
jsonschema                4.4.0                    pypi_0    pypi
kiwisolver                1.3.2            py39h295c915_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h7f8727e_2  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
libxslt                   1.1.34               hc22bd24_0  
locket                    0.2.1                    pypi_0    pypi
lxml                      4.8.0            py39h1f438cf_0  
lz4                       4.0.0                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
mako                      1.2.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1            py39h06a4308_1  
matplotlib-base           3.5.1            py39ha18d171_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
msgpack                   1.0.3                    pypi_0    pypi
munkres                   1.1.4                      py_0  
ncurses                   6.3                  h7f8727e_2  
numpy                     1.22.3                   pypi_0    pypi
openpyxl                  3.0.9                    pypi_0    pypi
openssl                   1.1.1m               h7f8727e_0  
orjson                    3.6.7                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.1                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       21.2.4           py39h06a4308_0  
prometheus-client         0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   7.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  1.9.0                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0  
pymongo                   4.0.2                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h2531618_6  
pyresttable               2020.0.3           pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-dotenv             0.19.2                   pypi_0    pypi
python-jose               3.3.0                    pypi_0    pypi
python-multipart          0.0.5                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
rfc3986                   1.5.0                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
setuptools                58.0.4           py39h06a4308_0  
sip                       4.19.13          py39h295c915_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0                    pypi_0    pypi
spec2nexus                2021.2.0           pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.32                   pypi_0    pypi
sqlite                    3.38.0               hc218d9a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
starlette                 0.17.1                   pypi_0    pypi
tifffile                  2022.3.16                pypi_0    pypi
tiled                     0.1.0a58                 pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
toolz                     0.11.2                   pypi_0    pypi
tornado                   6.1              py39h27cfd23_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typer                     0.4.0                    pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.8             pyhd3eb1b0_0  
uvicorn                   0.17.6                   pypi_0    pypi
uvloop                    0.16.0                   pypi_0    pypi
watchgod                  0.8                      pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
websockets                10.2                     pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xarray                    2022.3.0                 pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7f8727e_4  
zstd                      1.4.9                haebb681_0  
```

</details>
